### ISSUE TITLE
Undo/Trash Can Icon Issue

### ISSUE THREAD

**Issue by caseydemo** [bootcamp-f17/laravel-mail#46]
Per Melo's Comment on our pull request -->

Found an issue:

I am on a group message and I delete the message from my inbox
Somebody else clicks on that group message from their inbox
The delete button on their message has the undo icon instead of the trash can icon
The button still deletes, but the wrong icon is showing

**Comment by joncgrubb** [comment]
Fixed with exception of how messages are displayed within the Trash tab.
