### ISSUE TITLE
Test Cases

### ISSUE THREAD

**Issue by joncgrubb** [bootcamp-f17/laravel-mail#69]
**Inbox**
- All of current user's messages (that are not deleted) show in order of date / time.
- Starred messages show a star.
- Unread messages are highlighted.
- In show (view selected message) all fields are correct.
- Reply replies to the sender.
- Star and Trash buttons work.
- Back button returns user to Inbox.

**Sent**
- All of current user's non-deleted sent messages show in order of date / time.
- No star button on messages.
- In show, all fields are correct.
- Reply sends a reply message to current user.
- Delete button works.
- Back button returns user to Sent.

**Trash**
- All of current user's deleted messages show in the correct table in order of date / time.
- In show, all fields are correct.
- Reply should still work.
- Undeleting from each table works.
- Back button returns user to Trash.
- Delete a message sent by current user to another user.
- Delete a message received by current user from another user.
- Delete a message sent by current user to current user.
- Delete a multi-recipient message received by current user from another user.
- Delete a multi-recipient message sent by current user to other users, both including and not including current user as a recipient.
- Test delete toggle of all previous delete cases and ensure correct toggle button shows.
- Test if deleted starred messages retain a star after delete is toggled.

**Starred**
- All of my received messages that are starred show in order of date/time.
- Have star next to them.
- From/to/subject/date all show.
- Message body shows.
- Reply functions properly.
- Star highlighted - toggle off.
- Delete works - back button goes to starred.

**Drafts**
- All saved drafts show in order.
- Delete works, edit view tbd.
- Back button goes to drafts.

**Create**
- All recipients show up.
- Can select recipients.
- Filling in subject works and saves correctly when sent.
- Body fills in correctly & saves correctly when sent.
- Save turns message into draft.
- Send sends message to selected recipient.

**Comment by melanieps1** [comment]
I tested each of these cases and apart from known issues that are logged already, I didn't find anything else.

**Comment by caseydemo** [comment]
Link to our testing results: https://docs.google.com/spreadsheets/d/1u1k9YvhsevpNwk1Ar6McdUdTmwVpfE8TwUOLLd1E7NM/edit#gid=425835902

**Comment by melanieps1** [comment]
All test cases passed!
